# Generated by Django 4.1.2 on 2022-10-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circonscriptions', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.DateTimeField(auto_now=True)),
                ('bureau_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='circonscriptions.bureau')),
                ('canditaure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cni', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('a_voter', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.DateTimeField(auto_now=True)),
                ('bureau_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscrits', to='circonscriptions.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parti', models.CharField(blank=True, max_length=50, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.DateTimeField(auto_now=True)),
                ('electeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canditatues', to='electeurs.electeur')),
                ('elections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
    ]
