# Generated by Django 4.1.2 on 2022-10-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='electeurs.candidature'),
        ),
    ]
