# Generated by Django 4.1.2 on 2022-10-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
