# Generated by Django 4.1.2 on 2022-10-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('electeurs', '0003_alter_electeur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electeur',
            name='a_voter',
        ),
        migrations.CreateModel(
            name='ElecteurVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_voter', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.DateTimeField(auto_now=True)),
                ('canditaure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('eleteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electeurs.electeur')),
            ],
        ),
    ]
