# Generated by Django 4.1.2 on 2022-10-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0004_remove_electeur_a_voter_electeurvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electeurvote',
            old_name='canditaure',
            new_name='election',
        ),
        migrations.AlterField(
            model_name='vote',
            name='canditaure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electeurs.candidature'),
        ),
    ]
