# Generated by Django 4.1.2 on 2022-10-19 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electeurs', '0005_rename_canditaure_electeurvote_election_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electeurvote',
            name='a_voter',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='electeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='electeurs.electeur'),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electeurvote',
            name='eleteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='electeurs.electeur'),
        ),
    ]
