# Generated by Django 4.1.2 on 2022-10-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_nom'),
        ('electeurs', '0006_remove_electeurvote_a_voter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='electeur',
            new_name='candidat',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='elections',
        ),
        migrations.AddField(
            model_name='candidature',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='elections.election'),
        ),
    ]
