# Generated by Django 4.1.2 on 2022-10-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0007_rename_electeur_candidature_candidat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='canditaure',
            new_name='canditure',
        ),
    ]
