# Generated by Django 4.1.2 on 2022-10-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circonscriptions', '0003_alter_commune_nom_alter_departement_nom_and_more'),
        ('electeurs', '0009_remove_electeur_adresse_alter_electeur_numero_cni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='canditure',
            new_name='candidature',
        ),
        migrations.AlterField(
            model_name='electeur',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='bureau_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscrits', to='circonscriptions.bureau'),
        ),
    ]
