# Generated by Django 4.1.2 on 2022-10-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0011_alter_electeur_bureau_vote_alter_electeur_numero_cni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electeurvote',
            name='eleteur',
        ),
        migrations.AddField(
            model_name='electeurvote',
            name='electeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electeur', to='electeurs.electeur'),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='numero_cni',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
