# Generated by Django 4.1.2 on 2022-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_nom'),
        ('electeurs', '0012_remove_electeurvote_eleteur_electeurvote_electeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeurvote',
            name='electeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electeur', to='electeurs.electeur'),
        ),
        migrations.AlterField(
            model_name='electeurvote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
    ]
