# Generated by Django 4.1.2 on 2022-10-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_nom'),
        ('electeurs', '0013_alter_electeurvote_electeur_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electeurvote',
            unique_together={('electeur', 'election')},
        ),
    ]
