# Generated by Django 4.1.2 on 2022-10-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circonscriptions', '0003_alter_commune_nom_alter_departement_nom_and_more'),
        ('electeurs', '0014_alter_electeurvote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='electeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='electeurs.electeur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electeur',
            name='bureau_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrits', to='circonscriptions.bureau'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='bureau_vote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suffrages', to='circonscriptions.bureau'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electeurs.candidature'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('electeur', 'candidature')},
        ),
        migrations.DeleteModel(
            name='ElecteurVote',
        ),
    ]
