# Generated by Django 4.1.2 on 2022-10-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_vote', models.DateField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.DateTimeField(auto_now=True)),
                ('periode_depot_canditature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode_depot_canditature', to='elections.periode')),
                ('periode_inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode_inscription', to='elections.periode')),
            ],
        ),
    ]
