# Generated by Django 4.1.2 on 2022-10-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='periode_depot_canditature',
        ),
        migrations.RemoveField(
            model_name='election',
            name='periode_inscription',
        ),
        migrations.AddField(
            model_name='election',
            name='periode_depot_canditature_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='periode_depot_canditature_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='periode_inscription_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='periode_inscription_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Periode',
        ),
    ]
