# Generated by Django 4.1.2 on 2022-10-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_election_periode_depot_canditature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
