# Generated by Django 4.1.2 on 2022-10-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circonscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bureau',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
    ]
